#ifndef BASEDEFINE_H
#define BASEDEFINE_H

#define BOOTH_KEY_HEART "BOOTH_KEY_HEART"
#define BOOTH_KEY_TRIGGER "BOOTH_KEY_TRIGGER"
#define BOOTH_WEB_OPEN_READER "BOOTH_WEB_OPEN_READER"
#define BOOTH_WEB_OPEN_CARD "BOOTH_WEB_OPEN_CARD"
#define BOOTH_WEB_CPC_READ "BOOTH_WEB_CPC_READ"
#define BOOTH_WEB_CPC_WRITE "BOOTH_WEB_CPC_WRITE"
#define BOOTH_WEB_CPU_READ "BOOTH_WEB_CPU_READ"
#define BOOTH_WEB_CPU_WRITE "BOOTH_WEB_CPU_WRITE"
#define BOOTH_WEB_CARD_READ "BOOTH_WEB_CARD_READ"
#define BOOTH_WEB_CARD_WRITE "BOOTH_WEB_CARD_WRITE"
#define BOOTH_WEB_M1_READ "BOOTH_WEB_M1_READ"
#define BOOTH_WEB_PRINT_MSG "BOOTH_WEB_PRINT_MSG"
#define BOOTH_PSAM_AUTH "BOOTH_PSAM_AUTH"
#define BOOTH_PSAM_AUTHCONFIRM "BOOTH_PSAM_AUTHCONFIRM"

#endif // BASEDEFINE_H
